spring:
  application:
    name: mybatis-springboot
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_from_novice_to_expert?rewriteBatchedStatements=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  #json输出
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
# 日志
logging:
  level:
    root: INFO
    com.xjs1919.mybatis: DEBUG