server:
  port: 10010
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    loadbalancer:
      enabled: true # 默认就是true
      nacos:
        enabled: true # 默认没有开启
    gateway:
      discovery:
        locator:
          # true 默认路由机制
          # 开启服务注册和发现功能，服务网关自动根据服务发现为每一个服务创建一个路由，这个路由将以(大写服务名)开头的请求路径转发到对应的服务中
          # 访问地址：127.0.0.1:8800/大写服务名/服务上下文/Controller/Method
          #
          # false 关闭默认路由机制，需要手动配置routes，默认通过路由名进行跳转的方式将失效，将请求路径上的服务名配置为小写
          # 访问地址：127.0.0.1:8800/小写写服务名/服务上下文/Controller/Method
          enabled: false # 默认就是false
          lower-case-service-id: true
      routes:
        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/user/**






